package com.lilithsthrone.game.character.dirtyTalk;



//Méthode de travail : en remplir un de chaque catégorie puis écrire les variantes
public enum DomGentleDirtyTalk {
	

	DOM_GENTLE_PLAIN_NOPENETRATION_1("I'll be gentle, don't worry!"),
	DOM_GENTLE_PLAIN_NOPENETRATION_2("You're going to be a good [npc2.girl] now, aren't you?"),
	DOM_GENTLE_PLAIN_NOPENETRATION_3("Let's have some fun!"),
	DOM_GENTLE_CURIOUS_NOPENETRATION_1("Just relax... I don't know what to do with you yet, but i'll be great, don't worry..."),
	DOM_GENTLE_CURIOUS_NOPENETRATION_2("I can't wait to have fun with your body!"),
	DOM_GENTLE_CURIOUS_NOPENETRATION_3("I really wonder what kind of things you're into, [npc2.girl]..."),
	DOM_GENTLE_CAUTIOUS_NOPENETRATION_1("I think i'm going to go easy on you..."),
	DOM_GENTLE_CAUTIOUS_NOPENETRATION_2("Are you ready...? Sure...?"),
	DOM_GENTLE_CAUTIOUS_NOPENETRATION_3("I'll try to be gentle, little [npc2.girl]"),
	DOM_GENTLE_NICE_NOPENETRATION_1("relax, [npc2.girl]... We're going to have a great time!"),
	DOM_GENTLE_NICE_NOPENETRATION_2("You seems so tense... Don't worry, i know what i'm doing!"),
	DOM_GENTLE_NICE_NOPENETRATION_3("You're kinda cute, you know that?"),
	DOM_GENTLE_SELFISH_NOPENETRATION_1("I'm going to go easy on you... at first, at least."),
	DOM_GENTLE_SELFISH_NOPENETRATION_2("You're mine now... I can do what i want to you..."),
	DOM_GENTLE_SELFISH_NOPENETRATION_3("I'm going to have so much fun with that body of yours..."),
	DOM_GENTLE_CONFIDENT_NOPENETRATION_1("Ready for an awesome time, [npc2.girl]?"),
	DOM_GENTLE_CONFIDENT_NOPENETRATION_2("You're going to love this!"),
	DOM_GENTLE_CONFIDENT_NOPENETRATION_3("You are going to have the time of your life!"),
	DOM_GENTLE_SELFCONSCIOUS_NOPENETRATION_1("I... will go easy on you, okay?"),
	DOM_GENTLE_SELFCONSCIOUS_NOPENETRATION_2("I think you are going to love this..."),
	DOM_GENTLE_SELFCONSCIOUS_NOPENETRATION_3("I will try to make this perfect for you..."),
	DOM_GENTLE_SHY_NOPENETRATION_1("Hmm... I'm going to be gentle... So don't be afraid... allright?"),
	DOM_GENTLE_SHY_NOPENETRATION_2("...You're cute..."),
	DOM_GENTLE_SHY_NOPENETRATION_3("...I want you..."),
	DOM_GENTLE_FREAK_NOPENETRATION_1("Tee hee hee! I'm going to be REAL cute with you, i promise..."),
	DOM_GENTLE_FREAK_NOPENETRATION_2("Nyah hah hah! Am so excited right now..."),
	DOM_GENTLE_FREAK_NOPENETRATION_3("Fuck, fuck, fuck..."),
	DOM_GENTLE_COLD_NOPENETRATION_1("You, let me do my thing. You'll love it, don't worry about it."),
	DOM_GENTLE_COLD_NOPENETRATION_2("Relax..."),
	DOM_GENTLE_COLD_NOPENETRATION_3("Let's take our time."),
	DOM_GENTLE_CUTE_NOPENETRATION_1("I will do my best for your pleasure, i promise..."), 
	DOM_GENTLE_CUTE_NOPENETRATION_2("Hee hee..."),
	DOM_GENTLE_CUTE_NOPENETRATION_3("You're so cute... Just relax..."),
	DOM_GENTLE_JUDGING_NOPENETRATION_1("Come on, [npc2.girl]. i know that you can't wait for things to go further."),
	DOM_GENTLE_JUDGING_NOPENETRATION_2("Are you that desesperate? You look so excited right now..."),
	DOM_GENTLE_JUDGING_NOPENETRATION_3("I can't imagine how much your wishing for me to take you right now."),
	DOM_GENTLE_SAPIO_NOPENETRATION_1("What a cute [npc2.girl]... how about you just relax and let me help you reach the finest orgasm of your life?"),
	DOM_GENTLE_SAPIO_NOPENETRATION_2("You're a cute one. I think i'm going to take all my sweet time with you..."),
	DOM_GENTLE_SAPIO_NOPENETRATION_3("I really wonder how i'm going to make you come..."),
	DOM_GENTLE_LSE_NOPENETRATION_1("I... I really hope that you're going to like this..."),
	DOM_GENTLE_LSE_NOPENETRATION_2("I don't know if i'm really good at sex..."),
	DOM_GENTLE_LSE_NOPENETRATION_3("I'm kind of scared..."),
	DOM_GENTLE_TALKATIVE_NOPENETRATION_1("Are you ready? this is going to be quite fun!"),
	DOM_GENTLE_TALKATIVE_NOPENETRATION_2("Believe me... You're going to love this, [npc2.girl]..."),
	DOM_GENTLE_TALKATIVE_NOPENETRATION_3("So you're a submissive one, huh..."),
	DOM_GENTLE_INVASIVE_NOPENETRATION_1("Oh, i can't wait to fuck you! I'll be gentle at first, and then..."),
	DOM_GENTLE_INVASIVE_NOPENETRATION_2("You're my little [npc2.girl] now, just for me..."),
	DOM_GENTLE_INVASIVE_NOPENETRATION_3("I wonder if you like having things shoved in your ass..."),
	DOM_GENTLE_WORRIED_NOPENETRATION_1("I'll be gentle with you... I don't want to hurt you or anything..."),
	DOM_GENTLE_WORRIED_NOPENETRATION_2("It should not hurt... I'll be careful..."),
	DOM_GENTLE_WORRIED_NOPENETRATION_3("You seems kind of fragile... I'll go easy on you..."),
	DOM_GENTLE_CARING_NOPENETRATION_1("Just relax, love... I will be gentle with you, i promise..."),
	DOM_GENTLE_CARING_NOPENETRATION_2("You're going to love this, cute [npc2.girl]... I'll make that moment very, very good for you..."),
	DOM_GENTLE_CARING_NOPENETRATION_3("You're so cute, you know that...?"),
	DOM_GENTLE_DEGRADING_NOPENETRATION_1("Hey, [npc2.bitch]. i'll be gentle on you, i don't want to break you"),
	DOM_GENTLE_DEGRADING_NOPENETRATION_2("You little whore."),
	DOM_GENTLE_DEGRADING_NOPENETRATION_3("I'm going to enjoy taking my time with your worthless body..."),
	DOM_GENTLE_ENERGETIC_NOPENETRATION_1("This is going to be so great!"),
	DOM_GENTLE_ENERGETIC_NOPENETRATION_2("Oh, yes! yes!"),
	DOM_GENTLE_ENERGETIC_NOPENETRATION_3("You are making me horny, [npc2.girl]"),
	DOM_GENTLE_AW_NOPENETRATION_1("Oh, yes! Oh, yes! Oh, yes!"),
	DOM_GENTLE_AW_NOPENETRATION_2("I'm better at this than the others... You'll see..."),
	DOM_GENTLE_AW_NOPENETRATION_3("You-You're starting to get me very excited..."),
	DOM_GENTLE_PLAIN_GIVING_1("That's right, be a good [npc2.girl] and moan for me!"), 
	DOM_GENTLE_PLAIN_GIVING_2("Good [npc2.girl]!"),
	DOM_GENTLE_PLAIN_GIVING_3("You like that, huh?"),
	DOM_GENTLE_CURIOUS_GIVING_1("Do you like it? You kinda seems to like it... "),
	DOM_GENTLE_CURIOUS_GIVING_2("It must be so good for you, huh?"),
	DOM_GENTLE_CURIOUS_GIVING_3("It feels good...keep going..."),
	DOM_GENTLE_CAUTIOUS_GIVING_1("Does it feels good, [npc2.babe]?"),
	DOM_GENTLE_CAUTIOUS_GIVING_2("Here... Nice and slowly... You like that..?"),
	DOM_GENTLE_CAUTIOUS_GIVING_3("That's it... "),
	DOM_GENTLE_NICE_GIVING_1("Yeah, just like that..."),
	DOM_GENTLE_NICE_GIVING_2("It feels so good... You're a good little [npc2.girl]..."),
	DOM_GENTLE_NICE_GIVING_3("Keep it just that way, i love it..."),
	DOM_GENTLE_SELFISH_GIVING_1("ah, it feels so good!"),
	DOM_GENTLE_SELFISH_GIVING_2("You're my bitch now, all mine..."),
	DOM_GENTLE_SELFISH_GIVING_3("Let's keep going, shall we? I'm having a lot of fun with that body..."),
	DOM_GENTLE_CONFIDENT_GIVING_1("Looks like you're enjoying this!"),
	DOM_GENTLE_CONFIDENT_GIVING_2("Ah! This is awesome!"),
	DOM_GENTLE_CONFIDENT_GIVING_3("Yeah! Yeah! Yeah! Oh Yeah!"),
	DOM_GENTLE_SELFCONSCIOUS_GIVING_1("You like it, so far...? I'll keep going on, then..."),
	DOM_GENTLE_SELFCONSCIOUS_GIVING_2("Looks like i'm doing a good job..."),
	DOM_GENTLE_SELFCONSCIOUS_GIVING_3("Yeah... Just like that..."),
	DOM_GENTLE_SHY_GIVING_1("...It feels really good..."),
	DOM_GENTLE_SHY_GIVING_2("I love this..."),
	DOM_GENTLE_SHY_GIVING_3("Oh... Oh... Oh..."),
	DOM_GENTLE_FREAK_GIVING_1("Y'Like that? Y'like that?"),
	DOM_GENTLE_FREAK_GIVING_2("aHan aHan aHan aHan aHan"),
	DOM_GENTLE_FREAK_GIVING_3("I will make you scream like a little bitch..."),
	DOM_GENTLE_COLD_GIVING_1("...Looks like you're having a lot of fun."),
	DOM_GENTLE_COLD_GIVING_2("I like that..."),
	DOM_GENTLE_COLD_GIVING_3("You're not half-bad at this."),
	DOM_GENTLE_CUTE_GIVING_1("Hmm... It feels great..."),
	DOM_GENTLE_CUTE_GIVING_2("I love it... You're great at this..."),
	DOM_GENTLE_CUTE_GIVING_3("Aah..Aah..."),
	DOM_GENTLE_JUDGING_GIVING_1("Oh, look at you... You really like this kind of things, huh...?"),
	DOM_GENTLE_JUDGING_GIVING_2("Keep moaning like that... You're kind of a slut, you know? Hee hee."),
	DOM_GENTLE_JUDGING_GIVING_3("I can feel that you love this, [npc2.girl]"),
	DOM_GENTLE_SAPIO_GIVING_1("Oh, the pleasure of the flesh... That feeling is so overwhelming..."),
	DOM_GENTLE_SAPIO_GIVING_2("Yeah, this is perfect... Just like that..."),
	DOM_GENTLE_SAPIO_GIVING_3("Your body is really gorgeous, [npc2.girl]..."),
	DOM_GENTLE_LSE_GIVING_1("...I'am doing this right?"),
	DOM_GENTLE_LSE_GIVING_2("I like it... What about you...?"),
	DOM_GENTLE_LSE_GIVING_3("hnngh... aah..."),
	DOM_GENTLE_TALKATIVE_GIVING_1("Oh yes! yes! I can feel that you're loving this..."),
	DOM_GENTLE_TALKATIVE_GIVING_2("Keep going! I love it!"),
	DOM_GENTLE_TALKATIVE_GIVING_3("Cute little [npc2.girl]..."),
	DOM_GENTLE_INVASIVE_GIVING_1("Ahan! Ahan! Ahan!"),
	DOM_GENTLE_INVASIVE_GIVING_2("You like that, huh? You like that?"),
	DOM_GENTLE_INVASIVE_GIVING_3("You're moaning like a little bitch!"),
	DOM_GENTLE_WORRIED_GIVING_1("...Y-Yeah..."),
	DOM_GENTLE_WORRIED_GIVING_2("Tell me if i hurt you...I don't want to..."),
	DOM_GENTLE_WORRIED_GIVING_3("...So good..."),
	DOM_GENTLE_CARING_GIVING_1("Oh, [npc2.babe]... You like...?"),
	DOM_GENTLE_CARING_GIVING_2("I love it... You're perfect..."),
	DOM_GENTLE_CARING_GIVING_3("Hmm... This feels so good... Does it feel good for you too, [npc2.babe]?"),
	DOM_GENTLE_DEGRADING_GIVING_1("That's right, keep at it, slut."),
	DOM_GENTLE_DEGRADING_GIVING_2("You're really worthless, you know? I can do what i want with you right now..."),
	DOM_GENTLE_DEGRADING_GIVING_3("...You're so filthy..."),
	DOM_GENTLE_ENERGETIC_GIVING_1("Oh yes! yes! yes!"),
	DOM_GENTLE_ENERGETIC_GIVING_2("Yeah, take that!"),
	DOM_GENTLE_ENERGETIC_GIVING_3("You "),
	DOM_GENTLE_AW_GIVING_1("Oh, i'm so horny! Oh yes! Oh yes!"),
	DOM_GENTLE_AW_GIVING_2("You like it, [npc2.hun]? Yeah you like it!"),
	DOM_GENTLE_AW_GIVING_3("Yeah! I'm the best, huh?"),
	DOM_GENTLE_PLAIN_RECEIVING_1("DOM_GENTLE_PLAIN_RECEIVING_1"),
	DOM_GENTLE_PLAIN_RECEIVING_2("DOM_GENTLE_PLAIN_RECEIVING_2"),
	DOM_GENTLE_PLAIN_RECEIVING_3("DOM_GENTLE_PLAIN_RECEIVING_3"),
	DOM_GENTLE_CURIOUS_RECEIVING_1("DOM_GENTLE_CURIOUS_RECEIVING_1"),
	DOM_GENTLE_CURIOUS_RECEIVING_2("DOM_GENTLE_CURIOUS_RECEIVING_2"),
	DOM_GENTLE_CURIOUS_RECEIVING_3("DOM_GENTLE_CURIOUS_RECEIVING_3"),
	DOM_GENTLE_CAUTIOUS_RECEIVING_1("DOM_GENTLE_CAUTIOUS_RECEIVING_1"),
	DOM_GENTLE_CAUTIOUS_RECEIVING_2("DOM_GENTLE_CAUTIOUS_RECEIVING_2"),
	DOM_GENTLE_CAUTIOUS_RECEIVING_3("DOM_GENTLE_CAUTIOUS_RECEIVING_3"),
	DOM_GENTLE_NICE_RECEIVING_1("DOM_GENTLE_NICE_RECEIVING_1"),
	DOM_GENTLE_NICE_RECEIVING_2("DOM_GENTLE_NICE_RECEIVING_2"),
	DOM_GENTLE_NICE_RECEIVING_3("DOM_GENTLE_NICE_RECEIVING_3"),
	DOM_GENTLE_SELFISH_RECEIVING_1("DOM_GENTLE_SELFISH_RECEIVING_1"),
	DOM_GENTLE_SELFISH_RECEIVING_2("DOM_GENTLE_SELFISH_RECEIVING_2"),
	DOM_GENTLE_SELFISH_RECEIVING_3("DOM_GENTLE_SELFISH_RECEIVING_3"),
	DOM_GENTLE_CONFIDENT_RECEIVING_1("DOM_GENTLE_CONFIDENT_RECEIVING_1"),
	DOM_GENTLE_CONFIDENT_RECEIVING_2("DOM_GENTLE_CONFIDENT_RECEIVING_2"),
	DOM_GENTLE_CONFIDENT_RECEIVING_3("DOM_GENTLE_CONFIDENT_RECEIVING_3"),
	DOM_GENTLE_SELFCONSCIOUS_RECEIVING_1("DOM_GENTLE_SELFCONSCIOUS_RECEIVING_1"),
	DOM_GENTLE_SELFCONSCIOUS_RECEIVING_2("DOM_GENTLE_SELFCONSCIOUS_RECEIVING_2"),
	DOM_GENTLE_SELFCONSCIOUS_RECEIVING_3("DOM_GENTLE_SELFCONSCIOUS_RECEIVING_3"),
	DOM_GENTLE_SHY_RECEIVING_1("DOM_GENTLE_SHY_RECEIVING_1"),
	DOM_GENTLE_SHY_RECEIVING_2("DOM_GENTLE_SHY_RECEIVING_2"),
	DOM_GENTLE_SHY_RECEIVING_3("DOM_GENTLE_SHY_RECEIVING_3"),
	DOM_GENTLE_FREAK_RECEIVING_1("DOM_GENTLE_FREAK_RECEIVING_1"),
	DOM_GENTLE_FREAK_RECEIVING_2("DOM_GENTLE_FREAK_RECEIVING_2"),
	DOM_GENTLE_FREAK_RECEIVING_3("DOM_GENTLE_FREAK_RECEIVING_3"),
	DOM_GENTLE_COLD_RECEIVING_1("DOM_GENTLE_COLD_RECEIVING_1"),
	DOM_GENTLE_COLD_RECEIVING_2("DOM_GENTLE_COLD_RECEIVING_2"),
	DOM_GENTLE_COLD_RECEIVING_3("DOM_GENTLE_COLD_RECEIVING_3"),
	DOM_GENTLE_CUTE_RECEIVING_1("DOM_GENTLE_CUTE_RECEIVING_1"),
	DOM_GENTLE_CUTE_RECEIVING_2("DOM_GENTLE_CUTE_RECEIVING_2"),
	DOM_GENTLE_CUTE_RECEIVING_3("DOM_GENTLE_CUTE_RECEIVING_3"),
	DOM_GENTLE_JUDGING_RECEIVING_1("DOM_GENTLE_JUDGING_RECEIVING_1"),
	DOM_GENTLE_JUDGING_RECEIVING_2("DOM_GENTLE_JUDGING_RECEIVING_2"),
	DOM_GENTLE_JUDGING_RECEIVING_3("DOM_GENTLE_JUDGING_RECEIVING_3"),
	DOM_GENTLE_SAPIO_RECEIVING_1("DOM_GENTLE_SAPIO_RECEIVING_1"),
	DOM_GENTLE_SAPIO_RECEIVING_2("DOM_GENTLE_SAPIO_RECEIVING_2"),
	DOM_GENTLE_SAPIO_RECEIVING_3("DOM_GENTLE_SAPIO_RECEIVING_3"),
	DOM_GENTLE_LSE_RECEIVING_1("DOM_GENTLE_LSE_RECEIVING_1"),
	DOM_GENTLE_LSE_RECEIVING_2("DOM_GENTLE_LSE_RECEIVING_2"),
	DOM_GENTLE_LSE_RECEIVING_3("DOM_GENTLE_LSE_RECEIVING_3"),
	DOM_GENTLE_TALKATIVE_RECEIVING_1("DOM_GENTLE_TALKATIVE_RECEIVING_1"),
	DOM_GENTLE_TALKATIVE_RECEIVING_2("DOM_GENTLE_TALKATIVE_RECEIVING_2"),
	DOM_GENTLE_TALKATIVE_RECEIVING_3("DOM_GENTLE_TALKATIVE_RECEIVING_3"),
	DOM_GENTLE_INVASIVE_RECEIVING_1("DOM_GENTLE_INVASIVE_RECEIVING_1"),
	DOM_GENTLE_INVASIVE_RECEIVING_2("DOM_GENTLE_INVASIVE_RECEIVING_2"),
	DOM_GENTLE_INVASIVE_RECEIVING_3("DOM_GENTLE_INVASIVE_RECEIVING_3"),
	DOM_GENTLE_WORRIED_RECEIVING_1("DOM_GENTLE_WORRIED_RECEIVING_1"),
	DOM_GENTLE_WORRIED_RECEIVING_2("DOM_GENTLE_WORRIED_RECEIVING_2"),
	DOM_GENTLE_WORRIED_RECEIVING_3("DOM_GENTLE_WORRIED_RECEIVING_3"),
	DOM_GENTLE_CARING_RECEIVING_1("DOM_GENTLE_CARING_RECEIVING_1"),
	DOM_GENTLE_CARING_RECEIVING_2("DOM_GENTLE_CARING_RECEIVING_2"),
	DOM_GENTLE_CARING_RECEIVING_3("DOM_GENTLE_CARING_RECEIVING_3"),
	DOM_GENTLE_DEGRADING_RECEIVING_1("DOM_GENTLE_DEGRADING_RECEIVING_1"),
	DOM_GENTLE_DEGRADING_RECEIVING_2("DOM_GENTLE_DEGRADING_RECEIVING_2"),
	DOM_GENTLE_DEGRADING_RECEIVING_3("DOM_GENTLE_DEGRADING_RECEIVING_3"),
	DOM_GENTLE_ENERGETIC_RECEIVING_1("DOM_GENTLE_ENERGETIC_RECEIVING_1"),
	DOM_GENTLE_ENERGETIC_RECEIVING_2("DOM_GENTLE_ENERGETIC_RECEIVING_2"),
	DOM_GENTLE_ENERGETIC_RECEIVING_3("DOM_GENTLE_ENERGETIC_RECEIVING_3"),
	DOM_GENTLE_AW_RECEIVING_1("DOM_GENTLE_AW_RECEIVING_1"),
	DOM_GENTLE_AW_RECEIVING_2("DOM_GENTLE_AW_RECEIVING_2"),
	DOM_GENTLE_AW_RECEIVING_3("DOM_GENTLE_AW_RECEIVING_3");
	
	public String dialogue;
	
	DomGentleDirtyTalk(String dialogue){
		this.dialogue = dialogue;
	}
}
